"""
Ray Tuner API를 사용한 MAPPO 체크포인트 복원 및 이어서 학습

사용 예시:
python train_marllib_self/new_train_mappo_resume.py \
    --checkpoint ./train_marllib_self/experiments/mappo/run15_partial_obs \
    --iterations 100 \
    --run-name run15_resumed
"""

import os
os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import warnings
import ray
import logging
import json
import argparse
from datetime import datetime

# 경고 억제
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)
os.environ["PYTHONWARNINGS"] = "ignore::DeprecationWarning"

# Ray 로깅 설정
logging.getLogger("ray").setLevel(logging.ERROR)
logging.getLogger("ray.rllib").setLevel(logging.ERROR)
logging.getLogger("ray.tune").setLevel(logging.ERROR)

from ray.tune import Tuner, CLIReporter
from ray.air.config import RunConfig, CheckpointConfig
from ray.rllib.algorithms.mappo import MAPPO

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG


def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    config_dir.mkdir(parents=True, exist_ok=True)
    yaml_file = config_dir / "wildfire-ma.yaml"

    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_mappo_resume.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  MARLlib config file: {yaml_file}")
    return str(yaml_file)


def find_latest_checkpoint(directory):
    """디렉토리에서 최신 체크포인트를 찾기"""
    directory = Path(directory)
    if not directory.exists():
        return None

    checkpoints = []
    for item in directory.rglob("checkpoint_*"):
        if item.is_dir():
            try:
                iter_num = int(item.name.split("_")[1])
                checkpoints.append((iter_num, item))
            except (ValueError, IndexError):
                continue

    if not checkpoints:
        return None

    checkpoints.sort(key=lambda x: x[0], reverse=True)
    return str(checkpoints[0][1])


def find_params_json(checkpoint_dir):
    """체크포인트 디렉토리에서 params.json 파일 찾기"""
    checkpoint_path = Path(checkpoint_dir)
    current_dir = checkpoint_path if checkpoint_path.is_dir() else checkpoint_path.parent

    for _ in range(5):
        params_json = current_dir / "params.json"
        if params_json.exists():
            return str(params_json)

        parent = current_dir.parent
        if parent == current_dir:
            break
        current_dir = parent

    return None


def resume_training(
    checkpoint_path,
    num_iterations=100,
    checkpoint_freq=10,
    run_name=None
):
    """
    Ray Tuner API를 사용하여 체크포인트에서 복원하고 학습 재개

    Parameters
    ----------
    checkpoint_path : str
        복원할 체크포인트 경로
    num_iterations : int
        추가로 학습할 반복 횟수
    checkpoint_freq : int
        체크포인트 저장 빈도
    run_name : str
        실행 이름 (None이면 자동 생성)
    """

    checkpoint_path = os.path.abspath(checkpoint_path)
    checkpoint_path_obj = Path(checkpoint_path)

    # 디렉토리인 경우 최신 체크포인트 찾기
    if checkpoint_path_obj.is_dir() and not checkpoint_path_obj.name.startswith("checkpoint_"):
        latest = find_latest_checkpoint(checkpoint_path)
        if latest:
            checkpoint_path = latest
            print(f"최신 체크포인트: {checkpoint_path}")
        else:
            raise FileNotFoundError(f"체크포인트를 찾을 수 없습니다: {checkpoint_path}")

    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"체크포인트를 찾을 수 없습니다: {checkpoint_path}")

    # params.json 찾기
    params_json_path = find_params_json(checkpoint_path)
    if not params_json_path:
        raise FileNotFoundError(f"params.json을 찾을 수 없습니다: {checkpoint_path}")

    print(f"params.json: {params_json_path}")

    # 저장 디렉토리 설정
    if run_name is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"resumed_{timestamp}"

    save_dir = Path(__file__).parent / "experiments" / "mappo" / run_name
    save_dir.mkdir(parents=True, exist_ok=True)
    save_dir_str = str(save_dir)

    # Ray 초기화
    if ray.is_initialized():
        ray.shutdown()

    print("=" * 80)
    print("MAPPO 체크포인트 복원 및 학습 재개 (Ray Tuner API)")
    print("=" * 80)
    print(f"체크포인트: {checkpoint_path}")
    print(f"Params JSON: {params_json_path}")
    print(f"추가 반복: {num_iterations}")
    print(f"저장 디렉토리: {save_dir_str}")
    print("=" * 80)

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")

    # MARLlib 환경 등록
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib config 생성
    print(f"\nMARLlib 설정 파일 생성 중...")
    setup_marllib_config()

    # params.json에서 모델 아키텍처 정보 로드
    print(f"저장된 모델 설정 로드 중...")
    with open(params_json_path, 'r') as f:
        saved_config = json.load(f)

    model_arch_args = saved_config.get("model", {}).get("custom_model_config", {}).get("model_arch_args", {})
    print(f"  모델 아키텍처: {model_arch_args}")

    # Ray Tuner를 사용한 MAPPO 설정
    print(f"\nMAPPO 알고리즘 설정 중...")

    mappo_config = (
        MAPPO.get_default_config()
        .environment(
            env="wildfire-ma",
            env_config={
                "size": ENV_CONFIG['size'],
                "num_agents": ENV_CONFIG['num_agents'],
                "max_steps": ENV_CONFIG['max_steps'],
                "initial_fire_size": ENV_CONFIG['initial_fire_size'],
                "num_helicopters": ENV_CONFIG['num_helicopters'],
                "num_trucks": ENV_CONFIG['num_trucks'],
                "num_crews": ENV_CONFIG['num_crews'],
                "agent_start_positions": ENV_CONFIG['agent_start_positions'],
                "alpha": ENV_CONFIG['alpha'],
                "beta": ENV_CONFIG['beta'],
                "delta_beta": ENV_CONFIG['delta_beta'],
                "partial_obs": ENV_CONFIG['partial_obs'],
                "agent_view_size": ENV_CONFIG['agent_view_size'],
                "cooperative_reward": ENV_CONFIG['cooperative_reward'],
                "selfishness_weight": ENV_CONFIG['selfishness_weight'],
                "reward_shaping": ENV_CONFIG['reward_shaping'],
                "reward_shaping_config": ENV_CONFIG['reward_shaping_config'],
                "render_mode": ENV_CONFIG['render_mode'],
            }
        )
        .framework("torch")
        .rollouts(num_rollout_workers=2)
        .training(
            lr=0.0005,
            clip_param=0.3,
            entropy_coeff=0.01,
        )
        .resources(num_gpus=1)
    )

    # 체크포인트 설정
    checkpoint_config = CheckpointConfig(
        num_to_keep=5,
        checkpoint_frequency=checkpoint_freq,
        checkpoint_at_end=True,
    )

    # 실행 설정
    run_config = RunConfig(
        name=run_name,
        local_dir=str(save_dir.parent),
        stop={"training_iteration": num_iterations},
        checkpoint_config=checkpoint_config,
        progress_reporter=CLIReporter(),
    )

    print("\n" + "=" * 80)
    print("체크포인트에서 복원 중...")
    print("=" * 80 + "\n")

    # Tuner 생성
    tuner = Tuner(
        MAPPO,
        param_space=mappo_config.to_dict(),
        run_config=run_config,
    )

    # 체크포인트에서 복원하고 학습 실행
    try:
        results = tuner.fit()
        print("\n" + "=" * 80)
        print("학습 완료!")
        print("=" * 80)
        print(f"결과 저장 위치: {save_dir_str}")
        print("=" * 80)

        return save_dir_str
    except Exception as e:
        print(f"\n❌ 오류 발생: {e}")
        print(f"\n체크포인트 복원에 실패했습니다.")
        print(f"체크포인트 경로: {checkpoint_path}")
        print(f"가능한 원인:")
        print(f"  1. 체크포인트 파일이 손상되었을 수 있습니다")
        print(f"  2. Ray/RLlib 버전 호환성 문제일 수 있습니다")
        print(f"  3. 모델 아키텍처가 변경되었을 수 있습니다")
        raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ray Tuner를 사용한 MAPPO 체크포인트 복원")
    parser.add_argument(
        "--checkpoint",
        type=str,
        required=True,
        help="복원할 체크포인트 경로"
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=100,
        help="추가로 학습할 반복 횟수 (기본값: 100)"
    )
    parser.add_argument(
        "--checkpoint-freq",
        type=int,
        default=10,
        help="체크포인트 저장 빈도 (기본값: 10)"
    )
    parser.add_argument(
        "--run-name",
        type=str,
        default=None,
        help="실행 이름 (미지정 시 자동 생성)"
    )

    args = parser.parse_args()

    try:
        save_dir = resume_training(
            checkpoint_path=args.checkpoint,
            num_iterations=args.iterations,
            checkpoint_freq=args.checkpoint_freq,
            run_name=args.run_name
        )
        print(f"\n✓ 학습 재개 완료!")
        print(f"결과 경로: {save_dir}")
    except Exception as e:
        print(f"\n✗ 오류: {e}")
        sys.exit(1)
