"""
Train IA2C agents on wildfire suppression using new_wrapper.py

이 스크립트는 new_train_mappo.py의 구조를 따라서 new_wrapper.py를 사용하여
wildfire 환경에서 IA2C (Independent Advantage Actor-Critic) 에이전트를 학습시킵니다.

실행:
python train_marllib_self/new_train_a2c.py --run-name run1
"""

import os
os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG

import argparse
from datetime import datetime

def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    # MARLlib yaml 형식: env, env_args, mask_flag, global_state_flag 등
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_a2c.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    # 커맨드라인 인자 파싱 (선택적)
    parser = argparse.ArgumentParser(description='Train IA2C on Wildfire Environment')
    parser.add_argument('--run-name', type=str, default=None,
                       help='Run name for saving results (default: auto-generated)')
    args = parser.parse_args()

    # Run name 설정 (지정하지 않으면 자동 생성)
    if args.run_name:
        run_name = args.run_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"ia2c_{timestamp}"

    # 출력 디렉토리 설정
    output_dir = Path(__file__).parent / "experiments" / "ia2c" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Wildfire IA2C Training with new_wrapper")
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Output directory: {output_dir}")

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")
    print(f"  Crews: {ENV_CONFIG['num_crews']}")
    print(f"  Reward shaping: {ENV_CONFIG['reward_shaping']}")
    print(f"  Cooperative reward: {ENV_CONFIG['cooperative_reward']}")

    # MARLlib에 환경 등록 (add_new_env.py 방식)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (다른 컴퓨터에서도 작동)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        force_coop=False
    )

    # IA2C (Independent Advantage Actor-Critic) 알고리즘 선택
    # IA2C는 Independent Learning(IL) 기반으로 각 에이전트가 독립적으로 학습함
    # MAPPO와 달리 중앙화된 평가자(centralized critic)를 사용하지 않음
    print(f"IA2C 알고리즘 초기화 중...")
    ia2c = marl.algos.ia2c(
        hyperparam_source="common",
        batch_episode=10,
        # use_gae=True,         # Generalized Advantage Estimation 사용
        # lambda=1.0,           # GAE lambda 파라미터
        lr=0.0005,            # 학습률
        entropy_coeff=0.01    # 엔트로피 계수 (정책 탐색 장려)
    )

    # 모델 빌드
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        ia2c,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # MARLlib config에 필수 설정 추가 (ia2c() 호출 후에 수정)
    if ia2c.config_dict is not None:
        ia2c.config_dict["opp_action_in_cc"] = False
        ia2c.config_dict["global_state_flag"] = False
        ia2c.config_dict["local_dir"] = str(output_dir)  # 커스텀 출력 경로
    else:
        # config_dict가 None이면 직접 초기화
        ia2c.config_dict = {
            "opp_action_in_cc": False,
            "global_state_flag": False,
            "local_dir": str(output_dir)  # 커스텀 출력 경로
        }

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80 + "\n")

    ia2c.fit(
        env,
        model,
        stop={
            'episode_reward_mean': 50,
            'timesteps_total': 5000000,
            # 'training_iteration': 100
        },
        local_mode=False,  # GPU
        num_gpus=1,
        num_workers=2,
        share_policy='group',  # all, group, individual
        checkpoint_freq=25,
        local_dir=str(output_dir),  # fit() 메서드에 직접 전달
        evaluation_interval=None
    )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)
