"""
Train MAPPO agents on wildfire suppression using new_wrapper.py

이 스크립트는 add_new_env.py의 구조를 따라서 new_wrapper.py를 사용하여
wildfire 환경에서 MAPPO 에이전트를 학습시킵니다.

실행:
python train_marllib_self/new_train_mappo.py
"""

import sys
import os
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG


def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    # MARLlib yaml 형식: env, env_args, mask_flag, global_state_flag 등
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_mappo.py

env: wildfire

env_args:
  map_name: wildfire
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    print("=" * 80)
    print("Wildfire MAPPO Training with new_wrapper")
    print("=" * 80)

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")
    print(f"  Crews: {ENV_CONFIG['num_crews']}")
    print(f"  Reward shaping: {ENV_CONFIG['reward_shaping']}")
    print(f"  Cooperative reward: {ENV_CONFIG['cooperative_reward']}")

    # MARLlib에 환경 등록 (add_new_env.py 방식)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (다른 컴퓨터에서도 작동)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화
    # ENV_CONFIG는 래퍼의 __init__에서 사용되도록 env_args에 추가
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire",
        force_coop=True
    )

    # MAPPO 알고리즘 선택
    print(f"MAPPO 알고리즘 초기화 중...")
    mappo = marl.algos.mappo(hyperparam_source="common")

    # 모델 빌드
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        mappo,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80)
    print(f"  Share policy: all")
    print(f"  Workers: 2")
    print(f"  GPUs: 0")
    print(f"  Checkpoint frequency: 50")
    print(f"  Target reward: 1000")
    print(f"  Max timesteps: 5000000")
    print("=" * 80 + "\n")

    mappo.fit(
        env,
        model,
        stop={
            'episode_reward_mean': 1000,
            'timesteps_total': 5000000
        },
        local_mode=True,
        num_gpus=0,
        num_workers=2,
        share_policy='all',
        checkpoint_freq=50
    )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
