"""
Train MAPPO agents with custom output directory and run name

이 스크립트는 new_train_mappo.py를 기반으로 하되,
결과 저장 경로와 run name을 직접 지정할 수 있도록 확장한 버전입니다.

실행 예시:
# 기본 실행 (자동 생성된 run name 사용)
python train_marllib_self/train_mappo_custom.py

# run name 지정
python train_marllib_self/train_mappo_custom.py --run-name baseline_v1

# 커스텀 설정으로 실행
python train_marllib_self/train_mappo_custom.py --run-name high_lr --batch-episode 20 --lr 0.001

# iteration 기반 종료
python train_marllib_self/train_mappo_custom.py --run-name test_100iter --max-iterations 100
"""

import sys
import os
from pathlib import Path
import argparse
from datetime import datetime

project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG


def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by train_mappo_custom.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


def main(args):
    """메인 학습 함수"""

    print("=" * 80)
    print("Wildfire MAPPO Training (Custom Output Directory)")
    print("=" * 80)

    # Run name 생성
    if args.run_name:
        run_name = args.run_name
    else:
        # 자동 생성: mappo_YYYYMMDD_HHMMSS
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"mappo_{timestamp}"

    # 출력 디렉토리 설정
    output_base = Path(args.output_dir)
    output_dir = output_base / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n실행 설정:")
    print(f"  Run name: {run_name}")
    print(f"  Output directory: {output_dir}")

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")
    print(f"  Crews: {ENV_CONFIG['num_crews']}")
    print(f"  Reward shaping: {ENV_CONFIG['reward_shaping']}")
    print(f"  Cooperative reward: {ENV_CONFIG['cooperative_reward']}")

    # 학습 하이퍼파라미터 출력
    print(f"\n학습 하이퍼파라미터:")
    print(f"  Batch episode: {args.batch_episode}")
    print(f"  Num SGD iter: {args.num_sgd_iter}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Checkpoint frequency: {args.checkpoint_freq}")

    # 종료 조건 계산
    stop_conditions = {}
    if args.max_reward:
        stop_conditions['episode_reward_mean'] = args.max_reward
    if args.max_timesteps:
        stop_conditions['timesteps_total'] = args.max_timesteps
    if args.max_iterations:
        stop_conditions['training_iteration'] = args.max_iterations

    # 기본값: timesteps 또는 reward 중 하나라도 설정
    if not stop_conditions:
        stop_conditions = {
            'episode_reward_mean': 1000,
            'timesteps_total': 5000000
        }

    print(f"\n종료 조건:")
    for key, value in stop_conditions.items():
        print(f"  {key}: {value}")

    # MARLlib에 환경 등록
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        force_coop=False
    )

    # MAPPO 알고리즘 선택
    print(f"MAPPO 알고리즘 초기화 중...")

    # 알고리즘 파라미터 딕셔너리 생성
    algo_params = {}
    if args.batch_episode is not None:
        algo_params['batch_episode'] = args.batch_episode
    if args.num_sgd_iter is not None:
        algo_params['num_sgd_iter'] = args.num_sgd_iter
    if args.lr is not None:
        algo_params['lr'] = args.lr

    mappo = marl.algos.mappo(
        hyperparam_source="common",
        **algo_params
    )

    # 모델 빌드
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        mappo,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # MARLlib config에 필수 설정 추가
    if mappo.config_dict is not None:
        mappo.config_dict["opp_action_in_cc"] = False
        mappo.config_dict["global_state_flag"] = False
        # 커스텀 출력 디렉토리 설정
        mappo.config_dict["local_dir"] = str(output_dir)
    else:
        mappo.config_dict = {
            "opp_action_in_cc": False,
            "global_state_flag": False,
            "local_dir": str(output_dir)
        }

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80)
    print(f"  Share policy: all")
    print(f"  Workers: {args.num_workers}")
    print(f"  GPUs: {args.num_gpus}")
    print(f"  Local mode: {args.local_mode}")
    print("=" * 80 + "\n")

    mappo.fit(
        env,
        model,
        stop=stop_conditions,
        local_mode=args.local_mode,
        num_gpus=args.num_gpus,
        num_workers=args.num_workers,
        share_policy='all',
        checkpoint_freq=args.checkpoint_freq
    )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Train MAPPO with custom output directory",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # Run 설정
    parser.add_argument(
        '--run-name',
        type=str,
        default=None,
        help='Run name for this experiment (default: auto-generated with timestamp)'
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default='train_marllib_self/results/mappo',
        help='Base output directory (default: train_marllib_self/results/mappo)'
    )

    # 학습 하이퍼파라미터
    parser.add_argument(
        '--batch-episode',
        type=int,
        default=None,
        help='Number of episodes per training iteration (default: 10 from common config)'
    )
    parser.add_argument(
        '--num-sgd-iter',
        type=int,
        default=None,
        help='Number of SGD iterations per training batch (default: 5 from common config)'
    )
    parser.add_argument(
        '--lr',
        type=float,
        default=None,
        help='Learning rate (default: 0.0005 from common config)'
    )
    parser.add_argument(
        '--checkpoint-freq',
        type=int,
        default=50,
        help='Checkpoint frequency in iterations (default: 50)'
    )

    # 종료 조건
    parser.add_argument(
        '--max-reward',
        type=float,
        default=None,
        help='Stop when episode_reward_mean reaches this value'
    )
    parser.add_argument(
        '--max-timesteps',
        type=int,
        default=None,
        help='Stop when timesteps_total reaches this value'
    )
    parser.add_argument(
        '--max-iterations',
        type=int,
        default=None,
        help='Stop when training_iteration reaches this value'
    )

    # 실행 설정
    parser.add_argument(
        '--num-workers',
        type=int,
        default=2,
        help='Number of parallel workers (default: 2)'
    )
    parser.add_argument(
        '--num-gpus',
        type=int,
        default=1,
        help='Number of GPUs to use (default: 1)'
    )
    parser.add_argument(
        '--local-mode',
        action='store_true',
        help='Run in local mode (single process, easier debugging)'
    )

    args = parser.parse_args()

    main(args)
