"""
Train MADDPG agents on wildfire suppression using new_wrapper.py

이 스크립트는 new_wrapper.py를 사용하여
wildfire 환경에서 MADDPG 에이전트를 학습시킵니다.

*** 경고: MADDPG는 연속적인(Box) 액션 공간을 필요로 합니다. ***
*** new_wrapper.py의 action_space가 Box 타입인지 확인하세요. ***

실행:
python train_marllib_self/new_train_maddpg.py --run-name run1
"""

import os

# Ray Tune 리포터 간격 설정 (동일)
os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG

import argparse
from datetime import datetime

def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    # 이 함수는 환경 설정 파일만 생성하므로 MAPPO와 동일하게 작동합니다.
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_maddpg.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    # 커맨드라인 인자 파싱 (설명 변경)
    parser = argparse.ArgumentParser(description='Train MADDPG on Wildfire Environment')
    parser.add_argument('--run-name', type=str, default=None,
                       help='Run name for saving results (default: auto-generated)')
    args = parser.parse_args()

    # Run name 설정 (지정하지 않으면 자동 생성)
    if args.run_name:
        run_name = args.run_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"maddpg_{timestamp}" # 이름 변경

    # 출력 디렉토리 설정 (경로 변경)
    output_dir = Path(__file__).parent / "experiments" / "maddpg" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Wildfire MADDPG Training with new_wrapper") # 이름 변경
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Output directory: {output_dir}")

    # 환경 설정 출력 (동일)
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    # ... (기타 설정 동일)

    # MARLlib에 환경 등록 (동일)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (동일)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화 (동일)
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        force_coop=False
    )

    # --- 알고리즘 변경 ---
    print(f"MADDPG 알고리즘 초기화 중...")
    # maddpg = marl.algos.maddpg(
    #     hyperparam_source="common",
    #     batch_episode=10,
    #     # MADDPG는 actor와 critic의 학습률을 별도로 설정합니다.
    #     actor_lr=0.0005,
    #     critic_lr=0.0005
    #     # 'clip_param'은 PPO(MAPPO) 전용이므로 MADDPG에서는 제거합니다.
    # )

    masac = marl.algos.masac(
        hyperparam_source="common",
        batch_episode=10,
        # MASAC도 actor와 critic 학습률을 사용합니다.
        actor_lr=0.0005,
        critic_lr=0.0005
    )

    # 모델 빌드 (알고리즘 변수명 변경)
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        # maddpg, # mappo -> maddpg
        masac,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # MARLlib config에 필수 설정 추가 (알고리즘 변수명 변경)
    if masac.config_dict is not None:
        masac.config_dict["opp_action_in_cc"] = False
        masac.config_dict["global_state_flag"] = False
        masac.config_dict["local_dir"] = str(output_dir)
    else:
        masac.config_dict = {
            "opp_action_in_cc": False,
            "global_state_flag": False,
            "local_dir": str(output_dir)
    # if maddpg.config_dict is not None:
    #     maddpg.config_dict["opp_action_in_cc"] = False
    #     maddpg.config_dict["global_state_flag"] = False
    #     maddpg.config_dict["local_dir"] = str(output_dir)
    # else:
    #     maddpg.config_dict = {
    #         "opp_action_in_cc": False,
    #         "global_state_flag": False,
    #         "local_dir": str(output_dir)
        }

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80 + "\n")


    masac.fit( # mappo -> maddpg
        env,
        model,
        stop={
            'episode_reward_mean': 0,
            'timesteps_total': 5000000,
        },
        local_mode=False,
        num_gpus=1,
        num_workers=2,
        share_policy='group',
        checkpoint_freq=10,
        verbose=2,
        local_dir=str(output_dir),
        evaluation_interval=None
    )
    # maddpg.fit( # mappo -> maddpg
    #     env,
    #     model,
    #     stop={
    #         'episode_reward_mean': 0,
    #         'timesteps_total': 5000000,
    #     },
    #     local_mode=False,
    #     num_gpus=1,
    #     num_workers=2,
    #     share_policy='group',
    #     checkpoint_freq=10,
    #     verbose=2,
    #     local_dir=str(output_dir)
    # )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)