"""
Train MAPPO agents on wildfire suppression using new_wrapper.py

이 스크립트는 add_new_env.py의 구조를 따라서 new_wrapper.py를 사용하여
wildfire 환경에서 MAPPO 에이전트를 학습시킵니다.



실행:
python train_marllib_self/new_train_mappo.py --run-name run1
"""

import os

os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG

import argparse
from datetime import datetime

def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    # MARLlib yaml 형식: env, env_args, mask_flag, global_state_flag 등
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_mappo.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    # 커맨드라인 인자 파싱 (선택적)
    parser = argparse.ArgumentParser(description='Train MAPPO on Wildfire Environment')
    parser.add_argument('--run-name', type=str, default=None,
                       help='Run name for saving results (default: auto-generated)')
    args = parser.parse_args()

    # Run name 설정 (지정하지 않으면 자동 생성)
    if args.run_name:
        run_name = args.run_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"mappo_{timestamp}"

    # 출력 디렉토리 설정
    output_dir = Path(__file__).parent / "experiments" / "mappo" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Wildfire MAPPO Training with new_wrapper")
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Output directory: {output_dir}")

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")
    print(f"  Crews: {ENV_CONFIG['num_crews']}")
    print(f"  Reward shaping: {ENV_CONFIG['reward_shaping']}")
    print(f"  Cooperative reward: {ENV_CONFIG['cooperative_reward']}")

    # MARLlib에 환경 등록 (add_new_env.py 방식)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (다른 컴퓨터에서도 작동)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # TODO 49th iter 에러: 동적 policy_mapping_dict 자동 생성
    # 환경 초기화
    # ENV_CONFIG는 래퍼의 __init__에서 사용되도록 env_args에 추가
    # WildfireRLlibEnv.get_env_info()에서 동적으로 policy_mapping_dict 생성
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        force_coop=False
    )
    # 주의: marl.make_env() 호출 시 WildfireRLlibEnv.__init__이 호출되고,
    # 이후 env.get_env_info()에서 동적으로 policy_mapping_dict가 생성됨.
    # 모든 워커(main trainer, evaluation workers)가 일관된 정책을 받음.

    # # marl.make_env()는 튜플을 반환: (env, env_config)
    # if isinstance(env, tuple):
    #     env_real, _ = env
    # else:
    #     env_real = env

    # MAPPO 알고리즘 선택
    print(f"MAPPO 알고리즘 초기화 중...")
    mappo = marl.algos.mappo(
        hyperparam_source="common",
        batch_episode=10,
        # num_sgd_iter=10,  # SGD 반복 횟수 증가
        lr=0.0005,        # 학습률 조정
        clip_param=0.3
    )

    # # 환경에서 에이전트 타입별 개수 추출
    # num_helicopters = ENV_CONFIG['num_helicopters']
    # num_trucks = ENV_CONFIG['num_trucks']
    # num_crews = ENV_CONFIG['num_crews']

    # print(f"\n이질적 에이전트 설정:")
    # print(f"  헬리콥터: {num_helicopters}대")
    # print(f"  트럭: {num_trucks}대")
    # print(f"  인력: {num_crews}명")

    # # 모델 빌드 전에 공간 객체 저장
    # print(f"\n공간 객체 저장 중...")
    # obs_space = env_real.observation_space
    # action_space = env_real.action_space
    # print(f"  관찰 공간: {obs_space}")
    # print(f"  액션 공간: {action_space}")

    # 모델 빌드
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        mappo,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # MARLlib config에 필수 설정 추가 (mappo() 호출 후에 수정)
    if mappo.config_dict is not None:
        mappo.config_dict["opp_action_in_cc"] = False
        mappo.config_dict["global_state_flag"] = False
        mappo.config_dict["local_dir"] = str(output_dir)  # 커스텀 출력 경로
    else:
        # config_dict가 None이면 직접 초기화
        mappo.config_dict = {
            "opp_action_in_cc": False,
            "global_state_flag": False,
            "local_dir": str(output_dir)  # 커스텀 출력 경로
        }

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80 + "\n")

    mappo.fit(
        env,
        model,
        stop={
            'episode_reward_mean': 50,
            'timesteps_total': 5000000,
            # 'training_iteration': 100
        },
        local_mode=True, # GPU
        num_gpus=1,
        num_workers=2,
        share_policy='group', #all, group, individual
        # multi_agent_config={
        #     'policies': {
        #         'helicopter_policy': (None, obs_space, action_space, {}),
        #         'truck_policy': (None, obs_space, action_space, {}),
        #         'crew_policy': (None, obs_space, action_space, {}),
        #     },
        #     'policy_mapping_fn': lambda agent_id, *args, **kwargs: (
        #         "helicopter_policy" if agent_id < num_helicopters
        #         else "truck_policy" if agent_id < num_helicopters + num_trucks
        #         else "crew_policy"
        #     )
        # },
        checkpoint_freq=10,
        verbose=2,
        local_dir=str(output_dir),  # fit() 메서드에 직접 전달
        evaluation_interval=None

    )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)
