"""
Resume training MAPPO agents on wildfire suppression using checkpoint

이 스크립트는 기존 checkpoint에서 학습을 재개합니다.
new_train_mappo.py와 동일한 구조이지만, checkpoint 복구 기능이 추가됩니다.

실행:
python train_marllib_self/new_train_mappo_resume.py --checkpoint-path /path/to/checkpoint
python train_marllib_self/new_train_mappo_resume.py --restore /path/to/checkpoint --run-name continued_run


train_marllib_self/experiments/mappo/run6/mappo_mlp_wildfire-ma/MAPPOTrainer_wildfire-ma_wildfire-ma_ce091_00000_0_2025-11-16_16-10-44/checkpoint_000040
"""

import os

os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG

import argparse
from datetime import datetime

def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    # MARLlib yaml 형식: env, env_args, mask_flag, global_state_flag 등
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_mappo_resume.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False
global_state_flag: False
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file: {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    # 커맨드라인 인자 파싱
    parser = argparse.ArgumentParser(description='Resume MAPPO Training on Wildfire Environment')
    parser.add_argument('--checkpoint-path', type=str, default=None,
                       help='Checkpoint path to resume training from')
    parser.add_argument('--restore', type=str, default=None,
                       help='Checkpoint path to restore (alias for --checkpoint-path)')
    parser.add_argument('--run-name', type=str, default=None,
                       help='Run name for saving results (default: auto-generated with _resume suffix)')
    args = parser.parse_args()

    # Checkpoint 경로 결정
    checkpoint_path = args.checkpoint_path or args.restore
    if not checkpoint_path:
        print("ERROR: Checkpoint path is required!")
        print("Usage: python new_train_mappo_resume.py --checkpoint-path /path/to/checkpoint")
        print("   or: python new_train_mappo_resume.py --restore /path/to/checkpoint")
        sys.exit(1)

    # 경로 존재 확인
    checkpoint_path = Path(checkpoint_path)
    if not checkpoint_path.exists():
        print(f"ERROR: Checkpoint path does not exist: {checkpoint_path}")
        sys.exit(1)

    print(f"✓ Checkpoint found: {checkpoint_path}")

    # Run name 설정 (지정하지 않으면 자동 생성)
    if args.run_name:
        run_name = args.run_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"mappo_resume_{timestamp}"

    # 출력 디렉토리 설정
    output_dir = Path(__file__).parent / "experiments" / "mappo" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Wildfire MAPPO Training Resume with new_wrapper")
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Output directory: {output_dir}")
    print(f"Restoring from checkpoint: {checkpoint_path}")

    # 환경 설정 출력
    print(f"\n환경 설정:")
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    print(f"  Helicopters: {ENV_CONFIG['num_helicopters']}")
    print(f"  Trucks: {ENV_CONFIG['num_trucks']}")
    print(f"  Crews: {ENV_CONFIG['num_crews']}")
    print(f"  Reward shaping: {ENV_CONFIG['reward_shaping']}")
    print(f"  Cooperative reward: {ENV_CONFIG['cooperative_reward']}")

    # MARLlib에 환경 등록 (add_new_env.py 방식)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (다른 컴퓨터에서도 작동)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화
    # ENV_CONFIG는 래퍼의 __init__에서 사용되도록 env_args에 추가
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        force_coop=False
    )

    # MAPPO 알고리즘 선택
    print(f"MAPPO 알고리즘 초기화 중...")
    mappo = marl.algos.mappo(
        hyperparam_source="common",
        batch_episode=10,
        # num_sgd_iter=10,  # SGD 반복 횟수 증가
        lr=0.0005,        # 학습률 조정
        clip_param=0.3
        # algorithm_config={
        #     "clip_param": 0.3  # <-- We need algorithm_config for this
        # }
    )

    # 모델 빌드
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        mappo,
        {
            "core_arch": "mlp",
            "encode_layer": "256-256"
        }
    )

    # MARLlib config에 필수 설정 추가 (mappo() 호출 후에 수정)
    if mappo.config_dict is not None:
        mappo.config_dict["opp_action_in_cc"] = False
        mappo.config_dict["global_state_flag"] = False
        mappo.config_dict["local_dir"] = str(output_dir)  # 커스텀 출력 경로
    else:
        # config_dict가 None이면 직접 초기화
        mappo.config_dict = {
            "opp_action_in_cc": False,
            "global_state_flag": False,
            "local_dir": str(output_dir)  # 커스텀 출력 경로
        }

    # 학습 재개
    print("\n" + "=" * 80)
    print("학습 재개 (Resume)")
    print("=" * 80 + "\n")

    mappo.fit(
        env,
        model,
        stop={
            'episode_reward_mean': 100,
            'timesteps_total': 5000000,
            # 'training_iteration': 100
        },
        local_mode=False, # GPU
        num_gpus=1,
        num_workers=2,
        share_policy='group', #all, group, individual
        checkpoint_freq=10,
        verbose=2,
        local_dir=str(output_dir),  # fit() 메서드에 직접 전달
        restore=str(checkpoint_path)  # 중요: checkpoint에서 복구
    )

    print("\n" + "=" * 80)
    print("학습 재개 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)
