"""
Train MADQN (QMIX/VDN) agents on wildfire suppression using new_wrapper.py

이 스크립트는 new_wrapper.py를 사용하여
wildfire 환경에서 MADQN 에이전트를 학습시킵니다.

*** MADQN은 global_state_flag=True와 force_coop=True가 필수입니다. ***

실행:
python train_marllib_self/new_train_madqn.py --run-name run1
"""

import os

os.environ["TUNE_REPORTER_INTERVAL_S"] = "60"

import sys
from pathlib import Path
project_root = str(Path(__file__).parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from marllib.envs.global_reward_env import COOP_ENV_REGISTRY
from train_marllib_self.new_wrapper import WildfireRLlibEnv
from train_marllib_self.environment import ENV_CONFIG

import argparse
from datetime import datetime

def setup_marllib_config():
    """MARLlib 패키지 내부에 wildfire.yaml 설정 파일을 자동 생성"""
    import marllib
    marllib_path = Path(marllib.__file__).parent
    config_dir = marllib_path.parent / "examples" / "config" / "env_config"

    # 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    # yaml 파일 경로
    yaml_file = config_dir / "wildfire-ma.yaml"

    # yaml 파일 생성 (항상 최신 ENV_CONFIG로 업데이트)
    # MARLlib yaml 형식: env, env_args, mask_flag, global_state_flag 등
    yaml_content = f"""# Wildfire environment configuration for MARLlib
# Auto-generated by new_train_madqn.py

env: wildfire-ma

env_args:
  size: {ENV_CONFIG['size']}
  num_agents: {ENV_CONFIG['num_agents']}
  max_steps: {ENV_CONFIG['max_steps']}
  initial_fire_size: {ENV_CONFIG['initial_fire_size']}
  num_helicopters: {ENV_CONFIG['num_helicopters']}
  num_trucks: {ENV_CONFIG['num_trucks']}
  num_crews: {ENV_CONFIG['num_crews']}
  agent_start_positions: {ENV_CONFIG['agent_start_positions']}
  alpha: {ENV_CONFIG['alpha']}
  beta: {ENV_CONFIG['beta']}
  delta_beta: {ENV_CONFIG['delta_beta']}
  partial_obs: {ENV_CONFIG['partial_obs']}
  agent_view_size: {ENV_CONFIG['agent_view_size']}
  cooperative_reward: {ENV_CONFIG['cooperative_reward']}
  selfishness_weight: {ENV_CONFIG['selfishness_weight']}
  reward_shaping: {ENV_CONFIG['reward_shaping']}
  reward_shaping_config: {ENV_CONFIG['reward_shaping_config']}
  render_mode: {ENV_CONFIG['render_mode']}

mask_flag: False

# --- MADQN 핵심 변경 사항 ---
# QMIX/VDN은 중앙 믹서를 위해 전역 상태(global state)가 필요합니다.
global_state_flag: True
"""
    yaml_file.write_text(yaml_content)
    print(f"  Created/Updated config file (global_state_flag=True): {yaml_file}")

    return str(yaml_file)


if __name__ == '__main__':
    # 커맨드라인 인자 파싱 (설명 변경)
    parser = argparse.ArgumentParser(description='Train MADQN on Wildfire Environment')
    parser.add_argument('--run-name', type=str, default=None,
                       help='Run name for saving results (default: auto-generated)')
    args = parser.parse_args()

    # Run name 설정 (지정하지 않으면 자동 생성)
    if args.run_name:
        run_name = args.run_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"madqn_{timestamp}" # 이름 변경

    # 출력 디렉토리 설정 (경로 변경)
    output_dir = Path(__file__).parent / "experiments" / "madqn" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Wildfire MADQN (QMIX/VDN) Training with new_wrapper") # 이름 변경
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Output directory: {output_dir}")

    # 환경 설정 출력 (동일)
    print(f"\n환경 설정:")
    # ... (ENV_CONFIG 출력 부분은 MAPPO와 동일)
    print(f"  Grid size: {ENV_CONFIG['size']}x{ENV_CONFIG['size']}")
    print(f"  Agents: {ENV_CONFIG['num_agents']}")
    print(f"  Max steps: {ENV_CONFIG['max_steps']}")
    # ... (이하 동일)

    # MARLlib에 환경 등록 (동일)
    ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv
    COOP_ENV_REGISTRY["wildfire-ma"] = WildfireRLlibEnv

    # MARLlib 설정 파일 자동 생성 (YAML 내용이 변경됨)
    print(f"\nMARLlib 설정 파일 생성 중...")
    config_path = setup_marllib_config()

    # 환경 초기화
    print(f"환경 초기화 중...")
    env = marl.make_env(
        environment_name="wildfire-ma",
        map_name="wildfire-ma",
        # --- MADQN 핵심 변경 사항 ---
        # QMIX/VDN은 공동 보상을 가정합니다.
        force_coop=True
    )

    # --- 알고리즘 변경 ---
    print(f"MADQN (QMIX/VDN) 알고리즘 초기화 중...")
    madqn = marl.algos.madqn(
        hyperparam_source="common",
        # batch_episode=10, # Off-policy에서는 train_batch_size를 더 선호
        train_batch_size=512, # 리플레이 버퍼에서 샘플링할 크기
        buffer_size=100000,     # 경험 리플레이 버퍼 크기
        lr=0.0005,
        # 'clip_param'은 MAPPO 전용이므로 제거
    )

    # 모델 빌드 (알고리즘 변수명 변경)
    print(f"모델 빌드 중...")
    model = marl.build_model(
        env,
        madqn, # mappo -> madqn
        {
            # --- MADQN 핵심 변경 사항 ---
            # QMIX/VDN은 부분 관찰 문제를 해결하기 위해 RNN을 사용하는 것이 표준
            "core_arch": "rnn", 
            "encode_layer": "64-64" # RNN은 보통 MLP보다 작은 레이어를 사용
        }
    )

    # MARLlib config에 필수 설정 추가 (알고리즘 변수명 변경)
    if madqn.config_dict is not None:
        # --- MADQN 핵심 변경 사항 ---
        # 'opp_action_in_cc'는 Actor-Critic용이므로 제거
        madqn.config_dict["global_state_flag"] = True # YAML과 동일하게 True 명시
        madqn.config_dict["local_dir"] = str(output_dir)
    else:
        madqn.config_dict = {
            "global_state_flag": True,
            "local_dir": str(output_dir)
        }

    # 학습 시작
    print("\n" + "=" * 80)
    print("학습 시작")
    print("=" * 80 + "\n")

    madqn.fit( # mappo -> madqn
        env,
        model,
        stop={
            'episode_reward_mean': 0,
            'timesteps_total': 5000000,
        },
        local_mode=False,
        num_gpus=1,
        num_workers=2,
        share_policy='group', # QMIX/VDN은 보통 'all' (파라미터 공유)
        checkpoint_freq=10,
        verbose=2,
        local_dir=str(output_dir),
        evaluation_interval=None
    )

    print("\n" + "=" * 80)
    print("학습 완료!")
    print("=" * 80)
    print(f"결과 저장 위치: {output_dir}")
    print("=" * 80)